version: '3.7'

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    volumes:
      - static_volume:/app/backend/static_root
      - media_volume:/app/backend/media_root
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./docker/production/backend/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file: ./env/prod/.env
volumes:
  static_volume:
  media_volume:
